### ISSUE TITLE
Asking about multi PATH to multi websites

### ISSUE THREAD

**Issue by dqvn** [rceraline/private-aks-cluster#1]
Hi Rceraline, Thank you so much about your course! However, from the below configuration of deployment is just only support 1 domain to 1 resource, how can I apply 1 domain to link to multiple api services (microservices) 
For example:
1. http://api.mydomain.com/account -> backend.service: account-service:80
2. http://api.mydomain.com/booking -> backend.service: booking-service:80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-webapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  rules:
    - host: simple-webapp.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-webapp
                port:
                  number: 80

**Comment by rceraline** [comment]
Hi @dqvn,

You can update the ingress to support path based routing. You will end up with 1 ingress for both services.

Chances are that both of your backend services listen to the root path `/` instead of `/account` and `/booking`. If this is the case, you will also need to include the annotation `appgw.ingress.kubernetes.io/backend-path-prefix` to rewrite the URL. More information [here](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#backend-path-prefix).

Here is an example. Let me know if it works.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-webapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
    - host: simple-webapp.mydomain.com
      http:
        paths:
          - path: /account
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 80
          - path: /booking
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 80
```
